version: "3.8"
services:
  kafka-zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: kafka-zookeeper
    volumes:
      - ./data/zookeeper:/data
    networks:
      - kafka
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_MESSAGE_MAX_BYTES=2000000
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_HEAP_OPTS="-Xmx521M -Xms521M"
      - KAFKA_LOG_RETENTION_HOURS=1
    volumes:
      - ./data/kafka:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kafka-zookeeper
    networks:
      - kafka

  kafka-manager:
    image: sheepkiller/kafka-manager:stable
    hostname: kafka-manager
    ports:
      - "39000:9000"
    environment:
      ZK_HOSTS: kafka-zookeeper:2181
    depends_on:
      - kafka-zookeeper
      - kafka
    networks:
      - kafka

networks:
  kafka:
    driver: bridge