version: "3.8"
services:
  nginx:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - conf/nginx.conf:/etc/nginx/nginx.conf
      - data/:/data/
    restart: always
    ports:
      - "58080:80"

networks:
  nginx:
    driver: bridge