version: "3.8"
services:
  neo4j:
    image: neo4j:4.1.4
    volumes:
      - ./conf:/var/lib/neo4j/conf
      - ./import:/var/lib/neo4j/import
      - ./plugins:/var/lib/neo4j/plugins
      - ./data:/var/lib/neo4j/data
      - ./logs:/var/lib/neo4j/logs
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - env/neo4j.env
    networks:
      - neo4j

networks:
  neo4j:
    driver: bridge