version: "3.8"
services:
  neo4j:
    image: neo4j:4.1.4
    volumes:
      - ./conf:/var/lib/neo4j/conf
      - ./mnt:/var/lib/neo4j/import
      - ./plugins:/plugins
      - ./data:/data
      - ./logs:/var/lib/neo4j/logs
    restart: always
    ports:
      - "17474:7474"
      - "17687:7687"
    env_file:
      - env/neo4j.env
    networks:
      - neo4j

networks:
  neo4j:
    driver: bridge