version: "3.8"
services:
  kibana7:
    image: kibana:7.14.0
    container_name: kibana7
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 15601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
