version: "3.8"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es01
    restart: on-failure
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../elasticsearch/data01/data:/usr/share/elasticsearch/data
      - ../elasticsearch/data01/log:/usr/share/elasticsearch/log
      - ../elasticsearch/data01/logs:/usr/share/elasticsearch/logs
    ports:
      - 19200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es02
    restart: on-failure
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../elasticsearch/data02/data:/usr/share/elasticsearch/data
      - ../elasticsearch/data02/log:/usr/share/elasticsearch/log
      - ../elasticsearch/data02/logs:/usr/share/elasticsearch/logs
    ports:
      - 29200:9200
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es03
    restart: on-failure
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../elasticsearch/data03/data:/usr/share/elasticsearch/data
      - ../elasticsearch/data03/log:/usr/share/elasticsearch/log
      - ../elasticsearch/data03/logs:/usr/share/elasticsearch/logs
    ports:
      - 39200:9200
    networks:
      - elastic
  kibana7:
    image: kibana:7.16.2
    container_name: kibana7
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 15601:5601
    networks:
      - elastic
    depends_on:
      - es01
      - es02
      - es03
#volumes:
#  data01:
#    driver: local
#  data02:
#    driver: local
#  data03:
#    driver: local
networks:
  elastic:
    driver: bridge
