global:
  scrape_interval: 30s
  scrape_timeout: 20s
  evaluation_interval: 30s
  external_labels:
    env: QA
    cluster_name: specx-hadoop-qa

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: "pushgateway"
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: [ 'pushgateway:9091' ]
  - job_name: "graphite-exporter"
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'graphite-exporter:9108' ]



